source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'addressable'
gem 'fhir_client'
# gem 'fhir_client', :path => '../fhir_client'
gem 'rest-client'
gem 'time_difference'
gem 'pry'
gem 'rb-readline'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'base62-rb'
gem 'rake'
gem 'webmock'
gem 'rack-test'
gem 'json-jwt'
gem 'colorize'

gem 'simplecov', require: false, group: :test
