source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'addressable'
gem 'fhir_client', git: 'https://github.com/fhir-crucible/fhir_client.git', branch: 'r4'
gem 'fhir_models', git: 'https://github.com/fhir-crucible/fhir_models.git', branch: 'master'
gem 'fhir_stu3_models', git: 'https://github.com/fhir-crucible/fhir_stu3_models.git', branch: 'master'
gem 'fhir_dstu2_models', git: 'https://github.com/fhir-crucible/fhir_dstu2_models.git', branch: 'update_dep'
gem 'rest-client'
gem 'time_difference'
gem 'pry'
gem 'rb-readline'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'base62-rb'
gem 'rake'
gem 'webmock'
gem 'rack-test'
gem 'json-jwt'
gem 'colorize'
gem 'kramdown'
gem 'selenium-webdriver'
gem 'rubocop', require: false
gem 'bloomer'
gem 'sqlite3'

gem 'simplecov', require: false, group: :test
