# ERB may be used to add dynamic content to this file.
# https://docs.ruby-lang.org/en/2.7.0/ERB.html

development:
  adapter: postgresql
  database: inferno_community_dev
  username: postgres
  host: db
  pool: 10
  idle_timeout: 60

production:
  adapter: postgresql
  database: <%= ENV.fetch('INFERNO_DB_NAME', 'inferno_community_prod') %>
  username: <%= ENV.fetch('INFERNO_DB_USERNAME', 'postgres') %>
  host: <%= ENV.fetch('INFERNO_DB_HOST', 'db') %>
  pool: <%= ENV.fetch('INFERNO_DB_POOL_SIZE', '10') %>
  idle_timeout: <%= ENV.fetch('INFERNO_DB_IDLE_TIMEOUT', '60') %>

test: &test
  adapter: postgresql
  database: inferno_community_test
  username: postgres
  host: db
  pool: 10
  idle_timeout: 60
